version: "3"

services:
### NGINX ###
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/wordpress
    restart: on-failure
    ports:
      - "127.0.0.1:443:443"
    networks:
      - inception
### MARIADB ###
  mariadb:
    container_name: mariadb
    build: ./maria_db
    volumes:
      - database:/var/lib/mysql
    restart: on-failure
    ports:
      - "3306"
    env_file:
      - "./.env"
    networks:
      - inception
### WORDPRESS ###
  wordpress:
    container_name: wp-php7.3
    build: ./wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/wordpress
    restart: on-failure
    ports:
      - "9000"
    env_file:
      - "./.env"
    networks:
      - inception

networks:
  inception:

volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/thoberth/data/database
  wp:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/thoberth/data/wp