version: "3"

services:
### NGINX ###
  nginx:
    container_name: nginx
    build: srcs/nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
### MARIADB ###
  mariadb:
    container_name: mariadb
    build: srcs/maria_db
    volumes:
      - /home/thoberth/data/database:/var/lib/mysql
    restart: always
    ports:
      - "3306"
    env_file:
      - "srcs/.env"
    networks:
      - inception
### WORDPRESS ###
  wordpress:
    container_name: wp-php7.3
    build: srcs/wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/thoberth/data/wp:/var/www/html
    restart: always
    ports:
      - "9000"
    env_file:
      - "srcs/.env"
    networks:
      - inception

networks:
  inception: