version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "443:443"
  mariadb:
    image: mariadb
    volumes:
      - /home/berthetthomas/data/DB
    restart: always
    ports:
      - "3306:3306"
    #environment:
  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /home/berthetthomas/data/WordPress